.TH KINDLETOOL 1 05/03/12 Linux KindleTool
.SH NAME
KindleTool \- creates/extracts Kindle updates and more
.SH SYNOPSIS
.B kindletool
.I "<create|convert|extract|info|dm|md|version|help>" "[options]"
.SH DESCRIPTION
KindleTool will help you create or extract Kindle update packages
.SH OPTIONS
.SS create
.TP
.RB < ota | ota2 | recovery >
Set the update type.
.TP
.BI \-d\  device \fR,\ \fB\-\-device= device
Set the target device.
.I device
is one of
.B k1\fR,\ \fBk2\fR,\ \fBk2i\fR,\ \fBdx\fR,\ \fBdxi\fR,\ \fBdxg\fR,\ \fBk3w\fR,\ \fBk3g\fR,\ \fBk3gb\fR,\ \fBk4\fR,\ \fBk5w\fR\ or\ \fBk5g\fR.
.TP
.BR \-k ", " \-\-key\ \fRfile
Set the private key used to sign files & package.
.SS convert
.SS extract
.SS info
.SS dm
.SS md
.SS version
.SS help