.TH KINDLETOOL 1 05/03/12 Linux KindleTool
.SH NAME
KindleTool \- creates/extracts Kindle updates and more
.SH SYNOPSIS
.B kindletool
.RB < create | convert | extract | info | dm | md | version | help >
.RI [ options ]
.SH DESCRIPTION
KindleTool will help you create or extract Kindle update packages
.SH OPTIONS
.SS create
.TP
.RB < ota | ota2 | recovery >
Set the update type.
.TP
.BI \-d " device, " \-\-device= device
Set the target device.
.I device
is one of
.BR k1 ", " k2 ", " k2i ", " dx ", " dxi ", " dxg ", " k3w ", " k3g ", " k3gb ", " k4 ", " k5w " or " k5g .
.TP
.BR \-k ", " \-\-key " file"
Set the private key used to sign files & package.
.SS convert
.SS extract
.SS info
.SS dm
.SS md
.SS version
.SS help